[archive.backend]
files      = [ "/etc/luids/archive/backends.json" ]

[archive.service]
files      = [ "/etc/luids/archive/services.json" ]

[archive.api]
event   = "event"
dns     = "dns"
tls     = "tls"


[server]
listenuri  = "tcp://0.0.0.0:5821"
