[archive]
eventapi   = "event"
dnsapi     = "dns"
tlsapi     = "tls"

[backend]
files      = [ "/etc/luids/archive/backends.json" ]

[service]
files      = [ "/etc/luids/archive/services.json" ]

[grpc-archive]
listenuri  = "tcp://0.0.0.0:5821"
